language: d
sudo: false

os:
  - linux
  - osx

# use OSX 10.13 rather than default (10.11). see: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
osx_image: xcode9

d:
  - dmd
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.1
  - dmd-2.073.0
  - dmd-2.072.2
  - dmd-2.071.2
  - ldc
  - ldc-1.4.0
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.1
  - gdc

addons:
  mariadb: '10.1'
  apt:
    packages: [ libevent-dev ]

# MySQL is not installed by default on OSX build agents
before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install mysql && brew services start mysql; fi"

before_script:
    - mysql -u root -e 'SHOW VARIABLES LIKE "%version%";'
    - mysql -u root -e 'CREATE DATABASE mysqln_testdb;'
    - echo 'host=127.0.0.1;port=3306;user=root;pwd=;db=mysqln_testdb' > testConnectionStr.txt

install: ./travis-install-deps.sh
script: ./run-tests

# most builds are already defined, the matrix is used to test alternative db versions
matrix:
    include:
        - d: dmd
          addons:
            mariadb: '5.5'
            apt:
              packages: [ libevent-dev ]
          env: DB=mariadb-5.5

        - d: dmd
          services:
            - mysql
          addons:
            apt:
              packages: [ libevent-dev ]
          env: DB=mysql-default
# dmd 2.074.1 and the ldc equivalent (v1.4.0) have a problem with std.typecons.Nullable
# gdc will fail due to std.experimental.allocator
    allow_failures:
        - d: dmd-2.074.1
        - d: ldc-1.4.0
        - d: gdc
