language: d
sudo: false

d:
  - dmd
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.1
  - dmd-2.073.0
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.2
  - ldc
  - ldc-1.6.0-beta1
  - ldc-1.5.0
  - ldc-1.4.0
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.1
  - ldc-1.0.0
  - ldc-0.17.5
  - ldc-0.17.1
  - ldc-0.17.0
  - gdc
  - gdc-6.3.0
  - gdc-4.8.5

addons:
  mariadb: '10.1'
  apt:
    packages: [ libevent-dev ]

# MySQL is not installed by default on OSX build agents
before_install:
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install mysql && brew services start mysql; fi"

before_script:
    - mysql -u root -e 'SHOW VARIABLES LIKE "%version%";'
    - mysql -u root -e 'CREATE DATABASE mysqln_testdb;'
    - echo 'host=127.0.0.1;port=3306;user=root;pwd=;db=mysqln_testdb' > testConnectionStr.txt

install: ./travis-install-deps.sh
script: ./run-tests

matrix:
    # Test alternative db versions, but only on one compiler version
    include:
        - d: dmd-2.070.2
          addons:
            mariadb: '5.5'
            apt:
              packages: [ libevent-dev ]
          env: DB=mariadb-5.5

        - d: dmd-2.070.2
          services:
            - mysql
          addons:
            apt:
              packages: [ libevent-dev ]
          env: DB=mysql-default

        # on Mac just test latest & oldest supported dmd and ldc
        - d: dmd
          os: osx
          osx_image: xcode9 # use OSX 10.13

        - d: ldc
          os: osx
          osx_image: xcode9 # use OSX 10.13

        - d: dmd-2.068.2
          os: osx

        - d: ldc-0.17.0
          os: osx

    allow_failures:
        # Doesn't appear to exist on travis: https://github.com/travis-ci/travis-ci/issues/8849
        - d: gdc-6.3.0
